#!/bin/sh

Volume_down() {
	sh -c "pactl set-sink-mute 0 false; pactl set-sink-volume 0 -$1%"
}

Volume_up() {
	VOL=$(pactl list sinks | grep "Volume: front" | awk -F'[/|/]' '{print $4}' | cut -d% -f1)
	if [[ VOL -ne 100 ]]; then
			sh -c "pactl set-sink-mute 0 false; pactl set-sink-volume 0 +$1%"
	fi
}

Usage() {
	echo "Usage: pvolume [option] <percentage>

  -d          Reduce volume by given percentage
  -u          Increase volume by given percentage
  -h,--help   Show this help text
	"
}

case $1 in
	-d  		) Volume_down $2
		 		;;
	-u  		) Volume_up $2
		 		;;
	-h|--help 	) Usage
		 		;;
esac