#!bin/sh

Wifi() {
	WIFI_QUALITY_INT=$(acpi --battery | cut -d, -f2 | cut -d% -f1)
	ESSID=$(wicd-cli --wireless -d | grep Essid |cut -d: -f2 | cut -b2-)
	BATSTATE=$(acpi | cut -d: -f2| cut -d, -f1 | cut -b2-)
	WIFI=""
			if [[ -n $ESSID ]]; then
				WIFI="$ESSID \ue04b"
			else
				WIFI="___  ⋅⋅⋅\ᵘᵉ²¹ᵇ"
			fi

	echo "$WIFI | "
}

# Print the percentage
while true; do
	
	echo -e "%{r}%{F#FF000000} $(Wifi)"
        sleep 1;
done