#! /bin/sh

nitrogen --restore &
sxhkd &
bar & 

bspc monitor -d I II III

bspc config border_width         0
bspc config window_gap           8
bspc config top_padding         25
bspc config left_padding        20
bspc config right_padding       20
bspc config bottom_padding      20

bspc config split_ratio           0.60
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config focus_follows_pointer true
bspc config click_to_focus        true

bspc rule -a baka-mplayer state=floating
bspc rule -a Gcolor3 state=floating
bspc rule -a Connman-gtk state=floating
bspc rule -a Avahi-discover state=floating
bspc rule -a MPlayer state=floating
bspc rule -a Nitrogen state=floating command="xdotool windowmove {} 50 100"
bspc rule -a Pavucontrol state=floating
bspc rule -a Viewnior state=floating
bspc rule -a Wicd-client.py state=floating
bspc rule -a XTerm state=floating
bspc rule -a "" state=floating
